/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "FileStoreBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "Hono": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "IndexSchedulerDlq": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "IndexSchedulerQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "IndexSchedulerSubscriberFunction": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "IndexStoreBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}